import Head from 'next/head'
import Nav from '../components/Nav'
import UpComingMovies from '../components/UpComingMovies'
import styles from '/styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>TOGETHER CINEMA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </Head>

      <Nav/>
      <UpComingMovies maxItem={12}/>
    </div>
  )
}
